// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKnJRQ0Qgj5Cyf6VMkPr9JLAC6nKetROg',
    appId: '1:1048935741394:web:cb06e5305f6097cb763a0b',
    messagingSenderId: '1048935741394',
    projectId: 'fischflosse-9ebcf',
    authDomain: 'fischflosse-9ebcf.firebaseapp.com',
    storageBucket: 'fischflosse-9ebcf.firebasestorage.app',
    measurementId: 'G-GRPE9G3Q8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4AWOQ0fsNPkEBS-2Zn0PS9mnqDNFLeFo',
    appId: '1:1048935741394:android:acb338abb0636342763a0b',
    messagingSenderId: '1048935741394',
    projectId: 'fischflosse-9ebcf',
    storageBucket: 'fischflosse-9ebcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwhWN5bn7Mhze1O07VE_2LW_-BLgoC0lA',
    appId: '1:1048935741394:ios:2d86deafe1fb2b17763a0b',
    messagingSenderId: '1048935741394',
    projectId: 'fischflosse-9ebcf',
    storageBucket: 'fischflosse-9ebcf.firebasestorage.app',
    iosClientId: '1048935741394-r4adc6t8lda5kmeremngr3o6jlkak634.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishChips',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwhWN5bn7Mhze1O07VE_2LW_-BLgoC0lA',
    appId: '1:1048935741394:ios:2d86deafe1fb2b17763a0b',
    messagingSenderId: '1048935741394',
    projectId: 'fischflosse-9ebcf',
    storageBucket: 'fischflosse-9ebcf.firebasestorage.app',
    iosClientId: '1048935741394-r4adc6t8lda5kmeremngr3o6jlkak634.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishChips',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKnJRQ0Qgj5Cyf6VMkPr9JLAC6nKetROg',
    appId: '1:1048935741394:web:c07a6f58fe093002763a0b',
    messagingSenderId: '1048935741394',
    projectId: 'fischflosse-9ebcf',
    authDomain: 'fischflosse-9ebcf.firebaseapp.com',
    storageBucket: 'fischflosse-9ebcf.firebasestorage.app',
    measurementId: 'G-E3D8MZS1PY',
  );
}
